spring:
  application:
    name: Product-Service

  config:
    import: optional:configserver:http://localhost:9121

  datasource:
    url: jdbc:postgresql://localhost:5432/product-service
    username: postgres
    password: admin
  flyway:
    enabled: true
    locations: classpath:db/migration

resilience4j:
  circuitbreaker:
    instances:
      reviews-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - feign.FeignException
        ignoredExceptions:
          - java.lang.IllegalArgumentException


server:
  port: ${SERVER_PORT}
